server:
  port: 7097
spring:
  application:
    name: provider-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 30 
    leaseExpirationDurationInSeconds: 60